# Generated by Django 4.1.2 on 2022-10-17 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.TextField(max_length=250)),
                ('body', models.TextField(max_length=10000)),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 17, 11, 0, 30, 371952))),
            ],
        ),
    ]
