# Generated by Django 4.1.2 on 2022-10-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 17, 11, 1, 34, 509021)),
        ),
    ]
